import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <main className="px-8">
          <p className="text-xl font-bold border-b py-2 text-center">
            Frontend Mentor Challenges
          </p>
          {children}
        </main>
      </body>
    </html>
  );
}
